name: Google Trends Scraper

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt
      - name: Install missing libraries
  run: sudo apt-get install -y libwoff2dec-bin libvpx7 libevent-2.1-7 libopus0 libgstreamer1.0-0 libgstreamer-plugins-base1.0-0 gstreamer1.0-plugins-good
    - name: Install browsers 
      run: playwright install 
    - name: Jalankan script
      run: |
        for url in $(cat urls.txt); do
          python scraper.py "$url"
        done
