name: Google Trends Scraper

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install requests
      - name: Cek isi direktori sebelum menjalankan script
  run: ls -l
    - name: Bersihkan folder data
      run: rm -f data/*.json  # Hapus semua file JSON di folder data
    - name: Jalankan script
      run: python scraper.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: google-trends-data
        path: data/*.json

- name: Cek isi direktori setelah menjalankan script
  run: ls -l
